### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by nolka** [gietos/dadata#50] opened 2021-05-07 12:43 UTC
I have laravel project and some deps is already uset recent version of doctrine/inflector.
When i try to install your lib, got error:

```
composer require kstkn/dadata
Using version ^1.2 for kstkn/dadata
./composer.json has been updated
Running composer update kstkn/dadata
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kstkn/dadata ^1.2 -> satisfiable by kstkn/dadata[v1.2.0].
    - kstkn/dadata v1.2.0 requires doctrine/inflector ^1.2 -> found doctrine/inflector[v1.2.0, ..., 1.4.x-dev] but the package is fixed to 2.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```

**Comment by kstkn** [comment] 2021-05-07 13:55
So the problem is with dependency locked to a specific version. Did you try resolving it as suggested?

**Comment by nolka** [comment] 2021-05-11 06:46
Yes, it works👍🏾

**Closed as completed** 2021-05-11 07:40 UTC
Labels: question
